modules/admin/models/BizRule.php
<?php

namespace app\modules\admin\models;

use Yii;
use yii\rbac\Rule;
use app\modules\admin\components\Configs;

/**
 * BizRule
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class BizRule extends \yii\base\Model
{
    /**
     * @var string name of the rule
     */
    public $name;

    /**
     * @var integer UNIX timestamp representing the rule creation time
     */
    public $createdAt;

    /**
     * @var integer UNIX timestamp representing the rule updating time
     */
    public $updatedAt;

    /**
     * @var string Rule classname.
     */
    public $className;

    /**
     * @var Rule
     */
    private $_item;

    /**
     * Initilaize object
     * @param \yii\rbac\Rule $item
     * @param array $config
     */
    public function __construct($item, $config = [])
    {
        $this->_item = $item;
        if ($item !== null) {
            $this->name = $item->name;
            $this->className = get_class($item);
        }
        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'className'], 'required'],
            [['className'], 'string'],
            [['className'], 'classExists']
        ];
    }

    /**
     * Validate class exists
     */
    public function classExists()
    {
        if (!class_exists($this->className)) {
            $message = Yii::t('rbac-admin', "Unknown class '{class}'", ['class' => $this->className]);
            $this->addError('className', $message);
            return;
        }
        if (!is_subclass_of($this->className, Rule::className())) {
            $message = Yii::t('rbac-admin', "'{class}' must extend from 'yii\rbac\Rule' or its child class", [
                    'class' => $this->className]);
            $this->addError('className', $message);
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('rbac-admin', 'Name'),
            'className' => Yii::t('rbac-admin', 'Class Name'),
        ];
    }

    /**
     * Check if new record.
     * @return boolean
     */
    public function getIsNewRecord()
    {
        return $this->_item === null;
    }

    /**
     * Find model by id
     * @param type $id
     * @return null|static
     */
    public static function find($id)
    {
        $item = Configs::authManager()->getRule($id);
        if ($item !== null) {
            return new static($item);
        }

        return null;
    }

    /**
     * Save model to authManager
     * @return boolean
     */
    public function save()
    {
        if ($this->validate()) {
            $manager = Configs::authManager();
            $class = $this->className;
            if ($this->_item === null) {
                $this->_item = new $class();
                $isNew = true;
            } else {
                $isNew = false;
                $oldName = $this->_item->name;
            }
            $this->_item->name = $this->name;

            if ($isNew) {
                $manager->add($this->_item);
            } else {
                $manager->update($oldName, $this->_item);
            }

            return true;
        } else {
            return false;
        }
    }

    /**
     * Get item
     * @return Item
     */
    public function getItem()
    {
        return $this->_item;
    }
}

modules/admin/models/User.php
<?php

namespace app\modules\admin\models;

use app\modules\admin\components\Configs;
use app\modules\admin\components\UserStatus;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 *
 * @property UserProfile $profile
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return Configs::instance()->userTable;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'in', 'range' => [UserStatus::ACTIVE, UserStatus::INACTIVE]],
        ];
    }
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => UserStatus::ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => UserStatus::ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
                'password_reset_token' => $token,
                'status' => UserStatus::ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public static function getDb()
    {
        return Configs::userDb();
    }
}

modules/admin/controllers/UserController.php
<?php
namespace app\modules\admin\controllers;
use app\modules\admin\components\UserStatus;
use app\modules\admin\models\form\ChangePassword;
use app\modules\admin\models\form\Login;
use app\modules\admin\models\form\PasswordResetRequest;
use app\modules\admin\models\form\ResetPassword;
use app\modules\admin\models\form\Signup;
use app\modules\admin\models\searchs\User as UserSearch;
use app\modules\admin\models\User;
use Yii;
use yii\base\InvalidParamException;
use yii\base\UserException;
use yii\filters\VerbFilter;
use yii\mail\BaseMailer;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
/**
 * User controller
 */
class UserController extends Controller {
	private $_oldMailPath;
	/**
	 * @inheritdoc
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'delete'   => [ 'post' ],
					'logout'   => [ 'post' ],
					'activate' => [ 'post' ],
				],
			],
		];
	}
	/**
	 * @inheritdoc
	 */
//	public function beforeAction( $action ) {
//		if ( parent::beforeAction( $action ) ) {
//			if ( Yii::$app->has( 'mailer' ) && ( $mailer = Yii::$app->getMailer() ) instanceof BaseMailer ) {
//				/* @var $mailer BaseMailer */
//				$this->_oldMailPath = $mailer->getViewPath();
//				$mailer->setViewPath( '@mdm/admin/mail' );
//			}
//			return true;
//		}
//		return false;
//	}
	/**
	 * @inheritdoc
	 */
//	public function afterAction( $action, $result ) {
//		if ( $this->_oldMailPath !== null ) {
//			Yii::$app->getMailer()->setViewPath( $this->_oldMailPath );
//		}
//		return parent::afterAction( $action, $result );
//	}
	/**
	 * Lists all User models.
	 * @return mixed
	 */
	public function actionIndex() {
		$searchModel  = new UserSearch();
		$dataProvider = $searchModel->search( Yii::$app->request->queryParams );
		return $this->render( 'index', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
		] );
	}
	public function actionUpdate( $id ) {
		$model = $this->findModel( $id );
		if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
			return $this->redirect( [ 'view', 'id' => $model->id ] );
		}
		return $this->render( 'update', [
			'model' => $model,
		] );
	}
	/**
	 * Displays a single User model.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionView( $id ) {
		return $this->render( 'view', [
			'model' => $this->findModel( $id ),
		] );
	}
	/**
	 * Deletes an existing User model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionDelete( $id ) {
		$this->findModel( $id )->delete();
		return $this->redirect( [ 'index' ] );
	}
	/**
	 * Login
	 * @return string
	 */
	public function actionLogin() {
		if ( ! Yii::$app->getUser()->isGuest ) {
			return $this->goHome();
		}
		$model = new Login();
		if ( $model->load( Yii::$app->getRequest()->post() ) && $model->login() ) {
			return $this->goBack();
		} else {
			return $this->render( 'login', [
				'model' => $model,
			] );
		}
	}
	/**
	 * Logout
	 * @return string
	 */
	public function actionLogout() {
		Yii::$app->getUser()->logout();
		return $this->goHome();
	}
	/**
	 * Signup new user
	 * @return string
	 */
	public function actionSignup() {
		$model = new Signup();
		if ( $model->load( Yii::$app->getRequest()->post() ) ) {
			if ( $user = $model->signup() ) {
				return $this->goHome();
			}
		}
		return $this->render( 'signup', [
			'model' => $model,
		] );
	}
	/**
	 * Request reset password
	 * @return string
	 */
	public function actionRequestPasswordReset() {
		$model = new PasswordResetRequest();
		if ( $model->load( Yii::$app->getRequest()->post() ) && $model->validate() ) {
			if ( $model->sendEmail() ) {
				Yii::$app->getSession()->setFlash( 'success', 'Check your email for further instructions.' );
				return $this->goHome();
			} else {
				Yii::$app->getSession()->setFlash( 'error', 'Sorry, we are unable to reset password for email provided.' );
			}
		}
		return $this->render( 'requestPasswordResetToken', [
			'model' => $model,
		] );
	}
	/**
	 * Reset password
	 * @return string
	 */
	public function actionResetPassword( ) {
//		try {
//			$model = new ResetPassword( $token );
//		} catch ( InvalidParamException $e ) {
//			throw new BadRequestHttpException( $e->getMessage() );
//		}
		if ( $model->load( Yii::$app->getRequest()->post() ) && $model->validate() && $model->resetPassword() ) {
			Yii::$app->getSession()->setFlash( 'success', 'New password was saved.' );
			return $this->goHome();
		}
		return $this->render( 'resetPassword', [
			'model' => $model,
		] );
	}
	/**
	 * Reset password
	 * @return string
	 */
	public function actionChangePassword() {
		$model = new ChangePassword();
		if ( $model->load( Yii::$app->getRequest()->post() ) && $model->change() ) {
			return $this->goHome();
		}
		return $this->render( 'change-password', [
			'model' => $model,
		] );
	}
	/**
	 * Activate new user
	 *
	 * @param integer $id
	 *
	 * @return type
	 * @throws UserException
	 * @throws NotFoundHttpException
	 */
	public function actionActivate( $id ) {
		/* @var $user User */
		$user = $this->findModel( $id );
		if ( $user->status == UserStatus::INACTIVE ) {
			$user->status = UserStatus::ACTIVE;
			if ( $user->save() ) {
				return $this->goHome();
			} else {
				$errors = $user->firstErrors;
				throw new UserException( reset( $errors ) );
			}
		}
		return $this->goHome();
	}
	/**
	 * Finds the User model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id
	 *
	 * @return User the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel( $id ) {
		if ( ( $model = User::findOne( $id ) ) !== null ) {
			return $model;
		} else {
			throw new NotFoundHttpException( 'The requested page does not exist.' );
		}
	}
}

modules/admin/views/user/_form.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\User */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="user-form">
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
				<?php $form = ActiveForm::begin(); ?>
                <div class="box-body">
                    <div class="box-footer">
						<?= Html::submitButton( $model->isNewRecord ? Yii::t( 'rbac-admin', 'Create' ) : Yii::t( 'rbac-admin', 'Update' ), [ 'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary' ] ) ?>
                    </div>
                </div>
				<?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

modules/admin/views/user/change-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\modules\admin\models\form\ChangePassword */

$this->title = Yii::t('rbac-admin', 'Change Password');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to change password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-change']); ?>
                <?= $form->field($model, 'oldPassword')->passwordInput() ?>
                <?= $form->field($model, 'newPassword')->passwordInput() ?>
                <?= $form->field($model, 'retypePassword')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('rbac-admin', 'Change'), ['class' => 'btn btn-primary', 'name' => 'change-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/admin/views/user/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\searchs\User */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title                   = Yii::t( 'rbac-admin', 'Users' );
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">
    <div class="box box-primary">
        <div class="box-header with-border">
			<?= Html::a( Yii::t( 'app', 'Create User' ), [ 'signup' ], [ 'class' => 'btn btn-success' ] ) ?>
        </div>
        <div class="box-body">
			<?=
			GridView::widget( [
				'dataProvider' => $dataProvider,
				'filterModel'  => $searchModel,
				'columns'      => [
					[ 'class' => 'yii\grid\SerialColumn' ],
					'username',
					'email:email',
					[
						'attribute' => 'status',
						'value'     => function ( $model ) {
							return $model->status == 0 ? 'Inactive' : 'Active';
						},
						'filter'    => [
							0  => 'Inactive',
							10 => 'Active'
						]
					],
					[
						'class'    => 'yii\grid\ActionColumn',
						'template' => '{view} {update}'
					],
//            [
//                'class' => 'yii\grid\ActionColumn',
//                'template' => Helper::filterActionColumn(['view','update', 'activate', 'delete']),
//                'buttons' => [
//                    'activate' => function($url, $model) {
//                        if ($model->status == 10) {
//                            return '';
//                        }
//                        $options = [
//                            'title' => Yii::t('rbac-admin', 'Activate'),
//                            'aria-label' => Yii::t('rbac-admin', 'Activate'),
//                            'data-confirm' => Yii::t('rbac-admin', 'Are you sure you want to activate this user?'),
//                            'data-method' => 'post',
//                            'data-pjax' => '0',
//                        ];
//                        return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, $options);
//                    }
//                    ]
//                ],
				],
			] );
			?>
        </div>
    </div>
</div>

modules/admin/views/user/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\modules\admin\models\form\Login */

$this->title = Yii::t('rbac-admin', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'username') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['user/request-password-reset']) ?>.
                    For new user you can <?= Html::a('signup', ['user/signup']) ?>.
                </div>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('rbac-admin', 'Login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/admin/views/user/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\modules\admin\models\form\PasswordResetRequest */

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('rbac-admin', 'Send'), ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/admin/views/user/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\modules\admin\models\form\ResetPassword */

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'retypePassword')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('rbac-admin', 'Save'), ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/admin/views/user/signup.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\modules\admin\models\form\Signup */
$this->title                   = Yii::t( 'rbac-admin', 'Signup' );
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-body">
                    <p>Please fill out the following fields to signup:</p>
					<?= Html::errorSummary( $model ) ?>
					<?php $form = ActiveForm::begin( [ 'id' => 'form-signup' ] ); ?>
					<?= $form->field( $model, 'username' ) ?>
					<?= $form->field( $model, 'email' ) ?>
					<?= $form->field( $model, 'password' )->passwordInput() ?>
					<?= $form->field( $model, 'retypePassword' )->passwordInput() ?>
                    <div class="box-footer">
						<?= Html::submitButton( Yii::t( 'rbac-admin', 'Signup' ), [
							'class' => 'btn btn-primary',
							'name'  => 'signup-button'
						] ) ?>
                    </div>
					<?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

modules/admin/views/user/update.php
<?php
/* @var $this yii\web\View */
/* @var $model app\models\UsersBase */
$this->title                   = $model->username;
$this->params['breadcrumbs'][] = [ 'label' => Yii::t( 'rbac-admin', 'Users' ), 'url' => [ 'index' ] ];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-update">
	<?= $this->render( '_form', [
		'model' => $model,
	] ) ?>
</div>

modules/admin/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\modules\admin\components\Helper;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('rbac-admin', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$controllerId = $this->context->uniqueId . '/';
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php
        if ($model->status == 0 && Helper::checkRoute($controllerId . 'activate')) {
            echo Html::a(Yii::t('rbac-admin', 'Activate'), ['activate', 'id' => $model->id], [
                'class' => 'btn btn-primary',
                'data' => [
                    'confirm' => Yii::t('rbac-admin', 'Are you sure you want to activate this user?'),
                    'method' => 'post',
                ],
            ]);
        }
        ?>
        <?php
        if (Helper::checkRoute($controllerId . 'delete')) {
            echo Html::a(Yii::t('rbac-admin', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]);
        }
        ?>
    </p>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'username',
            'email:email',
            'created_at:date',
            'status',
        ],
    ])
    ?>

</div>